import type { LancerActorType } from "./actor/lancer-actor";
import type { LancerItemType } from "./item/lancer-item";
export declare type LancerDocumentType = LancerItemType | LancerActorType;
export declare function WELCOME(changelog: string): string;
export declare const NEEDS_MAJOR_MIGRATION_VERSION = "0.9.0";
export declare const NEEDS_MINOR_MIGRATION_VERSION = "0.9.99";
export declare const COMPATIBLE_MIGRATION_VERSION = "0.1.0";
export declare const NEEDS_AUTOMATION_MIGRATION_VERSION = "1.0.3";
export declare const LANCER: {
    ASCII: string;
    log_prefix: "LANCER |";
    setting_migration: "systemMigrationVersion";
    setting_core_data: "coreDataVersion";
    setting_lcps: "installedLCPs";
    setting_stock_icons: "keepStockIcons";
    setting_welcome: "hideWelcome";
    setting_compcon_login: "compconLogin";
    setting_status_icons: "statusIconConfig";
    setting_automation: "automationOptions";
    setting_automation_switch: "automationSwitch";
    setting_automation_attack: "attackSwitch";
    setting_actionTracker: "actionTracker";
    setting_pilot_oc_heat: "autoOCHeat";
    setting_overkill_heat: "autoOKillHeat";
    setting_auto_structure: "autoCalcStructure";
    setting_dsn_setup: "dsnSetup";
    setting_square_grid_diagonals: "squareGridDiagonals";
    mech_items: LancerItemType[];
    pilot_items: LancerItemType[];
    weapon_items: LancerItemType[];
    npc_items: LancerItemType[];
};
export declare function friendly_entrytype_name(type: LancerItemType | LancerActorType, count?: number): string;
export declare const GENERIC_ITEM_ICON = "systems/lancer/assets/icons/generic_item.svg";
export declare function TypeIcon(type: string, macro?: boolean): string;
export declare function replace_default_resource(current: string, replacement: string | null): string;
